# Generated by Django 5.0.3 on 2024-03-21 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_given', models.DecimalField(decimal_places=4, default=0, max_digits=19, null=True)),
                ('amount_used', models.DecimalField(decimal_places=4, default=0, max_digits=19, null=True)),
                ('amount_remaining', models.DecimalField(decimal_places=4, default=0, max_digits=19, null=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('reward_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_deposit', to='website.savingstransaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
