# Generated by Django 5.0.3 on 2024-03-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_savingstransaction_date_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
