# Generated by Django 5.0.3 on 2024-03-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_userpoints_expires_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_used', models.DecimalField(decimal_places=4, default=0, max_digits=19, null=True)),
                ('purchase_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.savingstransaction')),
                ('user_points', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.userpoints')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userpoints',
            name='purchase_transactions',
            field=models.ManyToManyField(through='website.PointPurchaseTransaction', to='website.savingstransaction'),
        ),
    ]
